# Generated by Django 5.0.1 on 2024-01-23 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('brend', models.CharField(blank=True, max_length=255, null=True)),
                ('razmer', models.CharField(blank=True, max_length=255, null=True)),
                ('old_price', models.FloatField(default=0)),
                ('new_price', models.FloatField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='image/')),
                ('image2', models.ImageField(blank=True, upload_to='image/')),
                ('image3', models.ImageField(blank=True, upload_to='image/')),
                ('image4', models.ImageField(blank=True, upload_to='image/')),
                ('image5', models.ImageField(blank=True, upload_to='image/')),
                ('image6', models.ImageField(blank=True, upload_to='image/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='shop.category')),
            ],
        ),
    ]
